import { MenuCategory } from './types';

export const MENU_DATA: MenuCategory[] = [
  {
    id: 'lunch-specials',
    title: 'Lunch Specials (11am-3pm)',
    items: [
      {
        id: 'speedy-gonzales',
        name: 'Speedy Gonzales',
        description: 'A beef hard shell taco, a beef enchilada and your choice of rice or beans.',
        price: '$7.75',
        category: 'lunch-specials',
      },
      {
        id: 'lunch-special-1',
        name: 'Lunch Special #1',
        description: 'A Chile relleno topped with red sauce, a ground beef hard shell taco, served with lettuce, guacamole and beans.',
        price: '$8.99',
        category: 'lunch-specials',
      },
      {
        id: 'lunch-special-2',
        name: 'Lunch Special #2',
        description: 'A beef burrito topped with red sauce, served with rice and beans.',
        price: '$8.49',
        category: 'lunch-specials',
      },
      {
        id: 'lunch-special-3',
        name: 'Lunch Special #3',
        description: 'A bean burrito, a cheese enchilada, served with rice.',
        price: '$8.49',
        category: 'lunch-specials',
      },
      {
        id: 'lunch-special-4',
        name: 'Lunch Special #4',
        description: 'A beef enchilada, a taquito (filled with shredded beef cooked with onions, tomatoes and peppers), a beef taco and sour cream.',
        price: '$8.49',
        category: 'lunch-specials',
      },
      {
        id: 'lunch-special-5',
        name: 'Lunch Special #5',
        description: 'Shredded chicken (cooked with onions, peppers, and tomatoes) quesadilla, served with rice and beans.',
        price: '$8.75',
        category: 'lunch-specials',
      },
      {
        id: 'tamale-verde',
        name: 'Tamale Verde',
        description: 'A pork tamal, topped with cheese dip and salsa verde served with rice and beans.',
        price: '$8.49',
        category: 'lunch-specials',
      },
      {
        id: 'chimichanga-lunch',
        name: 'Chimichanga',
        description: 'Topped with our queso dip sauce, served with lettuce, sour cream, guacamole, refried beans and rice.',
        price: '$9.75',
        category: 'lunch-specials',
      },
      {
        id: 'taco-salad-lunch',
        name: 'Taco Salad',
        description: 'A crispy golden-brown flour tortilla, filled with our seasoned ground beef or our shredded chicken and cheese. Topped with lettuce, tomatoes, and sour cream.',
        price: '$8.99',
        category: 'lunch-specials',
      },
      {
        id: 'fajita-taco-salad-lunch',
        name: 'Fajita Taco Salad',
        description: 'A large golden brown crispy flour tortilla filled with your choice of chicken or steak strips grilled with peppers, onions and tomatoes. Topped with lettuce, sour cream, shredded cheese and a slice of tomato.',
        price: '$9.99',
        category: 'lunch-specials',
      },
      {
        id: 'lunch-fajitas-chicken',
        name: 'Lunch Fajitas (Chicken)',
        description: 'Sizzling chicken strips with peppers, onions and tomatoes.',
        price: '$10.99',
        category: 'lunch-specials',
      },
      {
        id: 'lunch-fajitas-steak',
        name: 'Lunch Fajitas (Steak)',
        description: 'Sizzling steak strips with peppers, onions and tomatoes.',
        price: '$10.99',
        category: 'lunch-specials',
      },
      {
        id: 'seafood-lunch-fajita',
        name: 'Seafood Lunch Fajita',
        description: 'Sizzling seafood mix with peppers, onions and tomatoes.',
        price: '$12.49',
        category: 'lunch-specials',
      },
      {
        id: 'taquitos-mexicanos-lunch',
        name: 'Taquitos Mexicanos',
        description: 'Two corn tortillas filled with shredded chicken or beef, cooked with onions, peppers and tomatoes, wrapped and deep fried. Served with rice, beans, lettuce, pico de gallo, guacamole and sour cream.',
        price: '$8.99',
        category: 'lunch-specials',
      },
      {
        id: 'burrito-el-vaquero-lunch',
        name: 'Burrito El Vaquero',
        description: 'A large beef or chicken burrito, topped with red sauce, lettuce, sour cream, a slice of tomato and shredded cheese. Served with rice and beans.',
        price: '$9.49',
        category: 'lunch-specials',
      },
      {
        id: 'burritos-deluxe-lunch',
        name: 'Burritos Deluxe',
        description: 'One beef burrito and one shredded chicken burrito topped with lettuce and sour cream.',
        price: '$9.99',
        category: 'lunch-specials',
      },
      {
        id: 'huevos-con-chorizo',
        name: 'Huevos Con Chorizo',
        description: 'Scrambled eggs cooked with chorizo. Served with rice, beans and tortillas.',
        price: '$10.49',
        category: 'lunch-specials',
      },
      {
        id: 'huevos-rancheros',
        name: 'Huevos Rancheros',
        description: 'Eggs cooked over easy smothered with our ranchero sauce. Served with rice, beans and tortillas.',
        price: '$9.99',
        category: 'lunch-specials',
      },
      {
        id: 'burrito-huevos-chorizo',
        name: 'Burrito de Huevos con Chorizo',
        description: 'A large flour tortilla filled with scrambled eggs and chorizo topped with queso dip, served with rice and beans.',
        price: '$10.49',
        category: 'lunch-specials',
      }
    ]
  },
  {
    id: 'express-lunch',
    title: 'Express Lunch ($7.99)',
    items: [
      {
        id: 'express-taco',
        name: 'Taco, Rice and Beans',
        description: 'Beef or chicken taco served with rice and beans.',
        price: '$7.99',
        category: 'express-lunch',
      },
      {
        id: 'express-tamale',
        name: 'Tamale, Rice and Beans',
        description: 'Shredded pork tamale topped with seasoned ground beef and red sauce, served with rice and beans.',
        price: '$7.99',
        category: 'express-lunch',
      },
      {
        id: 'express-tostada',
        name: 'Tostada, Rice and Beans',
        description: 'A flat, crispy corn tortilla covered in ground beef, topped with lettuce, sour cream and a slice of tomato.',
        price: '$7.99',
        category: 'express-lunch',
      },
      {
        id: 'express-chalupa',
        name: 'Chalupa, Rice and Beans',
        description: 'A flat, crispy corn tortilla covered with beans, lettuce, guacamole and a slice of tomato.',
        price: '$7.99',
        category: 'express-lunch',
      },
      {
        id: 'express-enchilada',
        name: 'Enchilada, Rice and Beans',
        description: 'Beef or chicken enchilada served with rice and beans.',
        price: '$7.99',
        category: 'express-lunch',
      },
      {
        id: 'express-tostaguac',
        name: 'Tostaguac, Rice and Beans',
        description: 'A flat, crispy corn tortilla covered with beans, seasoned ground beef, topped with lettuce, guacamole and a slice of tomato.',
        price: '$7.99',
        category: 'express-lunch',
      }
    ]
  },
  {
    id: 'childrens-plates',
    title: "Children's Plates ($7.50)",
    items: [
      {
        id: 'child-mac-cheese',
        name: 'Mac & Cheese',
        description: 'The cheesy American classic served with your choice of french fries or rice.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-taco-plate',
        name: 'Taco Plate',
        description: 'A hard shell ground beef taco topped with lettuce and shredded cheese. Served with rice and refried beans.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-enchilada-plate',
        name: 'Enchilada Plate',
        description: 'A ground beef enchilada topped with red enchilada sauce served with rice and refried beans.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-burrito-plate',
        name: 'Burrito Plate',
        description: 'A small beef burrito topped with red burrito sauce. Served with rice and refried beans.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-quesadilla-plate',
        name: 'Quesadilla Plate',
        description: 'One small cheese quesadilla. Served with rice and refried beans.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-mini-nachos',
        name: 'Mini Nachos',
        description: 'Crispy tortilla chips covered with melted cheese.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-chicken-nuggets',
        name: 'Chicken Nuggets',
        description: 'Chicken nuggets served with french fries.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-mr-panchos',
        name: 'Mr. Panchos',
        description: 'A cheese burger served with tomato, lettuce and french fries.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-pollo-con-queso',
        name: 'Small Pollo Con Queso',
        description: 'Strips of grilled chicken covered in our Queso Dip Sauce, served with flour tortillas.',
        price: '$7.50',
        category: 'childrens-plates',
      },
      {
        id: 'child-taco-salad',
        name: 'Taco Salad',
        description: 'A small taco salad with ground beef or shredded chicken, lettuce, sour cream, a slice of tomato & cheese.',
        price: '$7.50',
        category: 'childrens-plates',
      }
    ]
  },
  {
    id: 'a-la-carte',
    title: 'A La Carte & Sides',
    items: [
      {
        id: 'side-enchilada-1',
        name: 'Enchilada (1)',
        description: 'Beef, chicken or cheese.',
        price: '$2.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-enchilada-3',
        name: 'Enchiladas (3)',
        description: 'Beef, chicken or cheese.',
        price: '$7.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-burrito-1',
        name: 'Burrito (1)',
        description: 'Beef or chicken.',
        price: '$5.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-burrito-2',
        name: 'Burritos (2)',
        description: 'Beef or chicken.',
        price: '$9.50',
        category: 'a-la-carte',
      },
      {
        id: 'side-bean-burrito-1',
        name: 'Bean Burrito (1)',
        description: 'Bean burrito topped with cheese sauce.',
        price: '$4.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-bean-burrito-2',
        name: 'Bean Burritos (2)',
        description: 'Bean burritos topped with cheese sauce.',
        price: '$8.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-taco-hard-1',
        name: 'Hard Shell Taco (1)',
        description: 'Beef or chicken.',
        price: '$2.50',
        category: 'a-la-carte',
      },
      {
        id: 'side-taco-hard-3',
        name: 'Hard Shell Tacos (3)',
        description: 'Beef or chicken.',
        price: '$6.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-taco-soft-1',
        name: 'Soft Shell Taco (1)',
        description: 'Beef or chicken.',
        price: '$2.75',
        category: 'a-la-carte',
      },
      {
        id: 'side-taco-soft-3',
        name: 'Soft Shell Tacos (3)',
        description: 'Beef or chicken.',
        price: '$7.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-tostada-1',
        name: 'Beef Tostada (1)',
        description: 'Beef tostada with lettuce and cheese.',
        price: '$5.49',
        category: 'a-la-carte',
      },
      {
        id: 'side-tostada-2',
        name: 'Beef Tostadas (2)',
        description: 'Beef tostadas with lettuce and cheese.',
        price: '$10.49',
        category: 'a-la-carte',
      },
      {
        id: 'side-chalupa-1',
        name: 'Chalupa (1)',
        description: 'Chalupa with beans, lettuce and guacamole.',
        price: '$4.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-chalupa-2',
        name: 'Chalupas (2)',
        description: 'Chalupas with beans, lettuce and guacamole.',
        price: '$7.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-tostaguac-1',
        name: 'Tostaguac (1)',
        description: 'Tostaguac with beans, beef and guacamole.',
        price: '$5.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-tostaguac-2',
        name: 'Tostaguacs (2)',
        description: 'Tostaguacs with beans, beef and guacamole.',
        price: '$10.49',
        category: 'a-la-carte',
      },
      {
        id: 'side-tamale-1',
        name: 'Tamale (1)',
        description: 'Pork tamale.',
        price: '$4.50',
        category: 'a-la-carte',
      },
      {
        id: 'side-tamale-2',
        name: 'Tamales (2)',
        description: 'Pork tamales.',
        price: '$8.49',
        category: 'a-la-carte',
      },
      {
        id: 'side-chile-relleno-1',
        name: 'Chile Relleno (1)',
        description: 'Chile relleno topped with red sauce.',
        price: '$4.50',
        category: 'a-la-carte',
      },
      {
        id: 'side-chile-relleno-2',
        name: 'Chile Rellenos (2)',
        description: 'Chile rellenos topped with red sauce.',
        price: '$8.49',
        category: 'a-la-carte',
      },
      {
        id: 'side-beans',
        name: 'Refried Beans',
        description: 'Creamy refried beans.',
        price: '$3.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-rice',
        name: 'Rice',
        description: 'Mexican style rice.',
        price: '$3.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-rice-beans',
        name: 'Rice and Beans',
        description: 'Mexican style rice and refried beans.',
        price: '$3.49',
        category: 'a-la-carte',
      },
      {
        id: 'side-rice-cheese',
        name: 'Rice with Cheese Dip',
        description: 'Mexican style rice topped with our famous cheese dip.',
        price: '$4.75',
        category: 'a-la-carte',
      },
      {
        id: 'side-sour-cream',
        name: 'Sour Cream',
        description: 'Cool and creamy sour cream.',
        price: '$1.50',
        category: 'a-la-carte',
      },
      {
        id: 'side-pico',
        name: 'Pico de Gallo',
        description: 'Freshly chopped tomatoes, onions, and cilantro.',
        price: '$1.99',
        category: 'a-la-carte',
      },
      {
        id: 'side-tortillas',
        name: 'Tortillas (3)',
        description: 'Three warm flour or corn tortillas.',
        price: '$1.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-tomatillo',
        name: 'Tomatillo Sauce',
        description: 'Spicy green tomatillo sauce.',
        price: '$1.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-chips-salsa',
        name: 'Chips and Salsa',
        description: 'Our signature chips and fresh salsa.',
        price: '$2.25',
        category: 'a-la-carte',
      },
      {
        id: 'side-fries',
        name: 'French Fries',
        description: 'Crispy golden french fries.',
        price: '$3.99',
        category: 'a-la-carte',
      }
    ]
  },
  {
    id: 'nachos',
    title: 'Nachos',
    items: [
      {
        id: 'nachos-cheese',
        name: 'Cheese Nachos',
        description: 'Simple and classic crispy chips topped with melted cheese.',
        price: '$7.99',
        category: 'nachos',
      },
      {
        id: 'nachos-cheese-bean',
        name: 'Cheese and Bean Nachos',
        description: 'Crispy chips topped with melted cheese and refried beans.',
        price: '$8.49',
        category: 'nachos',
      },
      {
        id: 'nachos-cheese-jalapeno',
        name: 'Cheese and Jalapeño Nachos',
        description: 'Crispy chips topped with melted cheese and spicy jalapeños.',
        price: '$8.49',
        category: 'nachos',
      },
      {
        id: 'nachos-cheese-beef',
        name: 'Cheese and Beef Nachos',
        description: 'Crispy chips topped with melted cheese and seasoned ground beef.',
        price: '$10.99',
        category: 'nachos',
      },
      {
        id: 'nachos-cheese-bean-beef',
        name: 'Cheese, Bean and Beef Nachos',
        description: 'Crispy chips topped with melted cheese, refried beans, and seasoned ground beef.',
        price: '$10.99',
        category: 'nachos',
      },
      {
        id: 'nachos-cheese-chicken',
        name: 'Cheese and Chicken Nachos',
        description: 'Crispy chips topped with melted cheese and shredded chicken.',
        price: '$9.99',
        category: 'nachos',
      },
      {
        id: 'nachos-el-vaquero',
        name: 'Nachos El Vaquero',
        description: 'A bed of crispy tortilla chips generously topped with cheese, beef, shredded chicken, refried beans, lettuce, tomatoes and sour cream.',
        price: '$11.49',
        category: 'nachos',
        image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&q=80&w=1000',
        featured: true,
      },
      {
        id: 'fajita-nachos',
        name: 'Fajita Nachos',
        description: 'A deliciously cheesy version of our sizzling fajitas, served over a bed of crispy tortilla chips and melted cheese. Choice of Steak or Chicken.',
        price: '$12.99',
        category: 'nachos',
      },
      {
        id: 'shrimp-fajita-nachos',
        name: 'Shrimp Fajita Nachos',
        description: 'Crispy chips topped with melted cheese and sizzling shrimp fajitas.',
        price: '$13.49',
        category: 'nachos',
      },
      {
        id: 'fajitas-bravas-nachos',
        name: 'Fajitas Bravas Nachos',
        description: 'A deliciously cheesy version of our sizzling fajitas bravas, served over a bed of crispy tortilla chips and melted cheese.',
        price: '$13.49',
        category: 'nachos',
      },
      {
        id: 'guacamole-dip',
        name: 'Guacamole Dip',
        description: 'Freshly made creamy guacamole dip.',
        price: '$4.99',
        category: 'nachos',
      },
      {
        id: 'queso-dip-large',
        name: 'Queso Dip',
        description: 'Our famous delicious cheese dip.',
        price: '$3.49',
        category: 'nachos',
      },
      {
        id: 'ground-beef-dip',
        name: 'Ground Beef Dip',
        description: 'Ground beef smothered in queso dip.',
        price: '$7.99',
        category: 'nachos',
      },
      {
        id: 'bean-dip-large',
        name: 'Bean Dip',
        description: 'Refried beans smothered in queso dip.',
        price: '$6.49',
        category: 'nachos',
      },
      {
        id: 'california-nachos',
        name: 'California Nachos',
        description: 'A bed of french fries topped with grilled steak strips and onions, topped with melted cheese and sour cream.',
        price: '$13.49',
        category: 'nachos',
      },
      {
        id: 'nachos-al-pastor',
        name: 'Nachos Al Pastor',
        description: 'A bed of crispy tortilla chips generously topped with cheese, al pastor marinated pork and grilled pineapple.',
        price: '$12.75',
        category: 'nachos',
      }
    ]
  },
  {
    id: 'burritos',
    title: 'Burritos',
    items: [
      {
        id: 'burrito-el-vaquero-dinner',
        name: 'Burrito El Vaquero',
        description: 'A large flour tortilla, filled with ground beef or shredded chicken. Topped with red sauce, lettuce, sour cream, a slice of tomato and shredded cheese. Served with rice and beans.',
        price: '$10.75',
        category: 'burritos',
      },
      {
        id: 'burritos-deluxe-dinner',
        name: 'Burritos Deluxe',
        description: 'One ground beef burrito and one shredded chicken burrito. Topped with lettuce, shredded cheese, sour cream and tomato.',
        price: '$10.75',
        category: 'burritos',
      },
      {
        id: 'burrito-ruleta',
        name: 'Burrito Ruleta',
        description: 'A shredded chicken burrito topped with our queso dip and pico de gallo, served with rice on the side.',
        price: '$9.99',
        category: 'burritos',
      },
      {
        id: 'burrito-special',
        name: 'Burrito Special',
        description: 'A ground beef burrito topped with red sauce, lettuce, cheese and sour cream.',
        price: '$8.99',
        category: 'burritos',
      },
      {
        id: 'burrito-mexicano',
        name: 'Burrito Mexicano',
        description: 'A large flour tortilla, filled with beef tips cooked with onions, bell peppers and tomatoes. Topped with our queso dip sauce, red sauce, lettuce, guacamole and a slice of tomato.',
        price: '$8.99',
        category: 'burritos',
      },
      {
        id: 'burrito-carne-asada',
        name: 'Burrito Carne Asada',
        description: 'A large flour tortilla, filled with grilled steak strips or chicken. Topped with our queso dip sauce. Served with rice and beans.',
        price: '$11.99',
        category: 'burritos',
      },
      {
        id: 'burritos-supremos',
        name: 'Burritos Supremos',
        description: 'Two burritos, one filled with grilled chicken, one filled with grilled steak. Covered in queso dip, served with rice and beans.',
        price: '$11.99',
        category: 'burritos',
      },
      {
        id: 'burrito-california',
        name: 'Burrito California',
        description: 'One big burrito filled with grilled chicken and steak strips, rice, beans and shredded cheese with a side of guacamole, pico and sour cream.',
        price: '$12.99',
        category: 'burritos',
        featured: true,
      },
      {
        id: 'burrito-carnitas',
        name: 'Burrito de Carnitas',
        description: 'A large flour tortilla filled with carnitas, topped with queso dip and pico de gallo. Served with rice and beans.',
        price: '$12.75',
        category: 'burritos',
      }
    ]
  },
  {
    id: 'quesadillas',
    title: 'Quesadillas',
    items: [
      {
        id: 'quesadilla-chicken-cheese',
        name: 'Chicken & Cheese Quesadilla',
        description: 'Large grilled tortilla filled with chicken and melted cheese.',
        price: '$12.75',
        category: 'quesadillas',
      },
      {
        id: 'quesadilla-half-chicken-cheese',
        name: 'Half Chicken & Cheese Quesadilla',
        description: 'Half portion of our chicken and cheese quesadilla.',
        price: '$9.99',
        category: 'quesadillas',
      },
      {
        id: 'quesadilla-cheese-only',
        name: 'Cheese Only Quesadilla',
        description: 'Simple and delicious melted cheese in a grilled tortilla.',
        price: '$5.99',
        category: 'quesadillas',
      },
      {
        id: 'quesadilla-beef-cheese',
        name: 'Ground Beef & Cheese Quesadilla',
        description: 'Large grilled tortilla filled with seasoned ground beef and melted cheese.',
        price: '$7.49',
        category: 'quesadillas',
      },
      {
        id: 'quesadilla-rellena',
        name: 'Quesadilla Rellena',
        description: 'Beans, cheese and your choice of shredded chicken or beef tips cooked with onions, tomatoes and peppers in between two large grilled tortillas. Served with lettuce, pico de gallo, guacamole and sour cream.',
        price: '$12.75',
        category: 'quesadillas',
      },
      {
        id: 'fajita-quesadilla',
        name: 'Fajita Quesadilla',
        description: 'Your choice of steak or chicken grilled with onions, peppers and tomatoes with cheese in between two large grilled flour tortillas. Served with lettuce, sour cream, guacamole and pico de gallo.',
        price: '$12.99',
        category: 'quesadillas',
      },
      {
        id: 'half-fajita-quesadilla',
        name: 'Half Fajita Quesadilla',
        description: 'Half portion of our sizzling fajita quesadilla.',
        price: '$9.99',
        category: 'quesadillas',
      },
      {
        id: 'shrimp-quesadilla',
        name: 'Shrimp Quesadilla',
        description: 'Marinated shrimp grilled with peppers, onions and tomatoes with cheese in between two large flour tortillas. Served with lettuce, sour cream, guacamole and a slice of tomato.',
        price: '$13.49',
        category: 'quesadillas',
      },
      {
        id: 'half-shrimp-quesadilla',
        name: 'Half Shrimp Quesadilla',
        description: 'Half portion of our marinated shrimp quesadilla.',
        price: '$10.49',
        category: 'quesadillas',
      },
      {
        id: 'fajitas-bravas-quesadilla',
        name: 'Fajitas Bravas Quesadilla',
        description: 'Grilled chicken, steak strips, shrimp, chorizo, peppers, onions and tomatoes with cheese in between two large grilled flour tortillas. Served with lettuce, sour cream, guacamole and pico de gallo.',
        price: '$13.99',
        category: 'quesadillas',
      }
    ]
  },
  {
    id: 'ensaladas',
    title: 'Ensaladas (Salads)',
    items: [
      {
        id: 'taco-salad-dinner',
        name: 'Taco Salad',
        description: 'A crispy golden-brown flour tortilla, filled with ground beef or shredded chicken. Topped with lettuce, tomatoes, guacamole, cheese and sour cream.',
        price: '$10.49',
        category: 'ensaladas',
      },
      {
        id: 'fajita-taco-salad-dinner',
        name: 'Fajita Taco Salad',
        description: 'A crispy golden-brown flour tortilla, filled with your choice of fajitas chicken or steak. Topped with lettuce, tomatoes, shredded cheese, sour cream and guacamole.',
        price: '$11.49',
        category: 'ensaladas',
      },
      {
        id: 'fajita-taco-salad-shrimp',
        name: 'Fajita Taco Salad (Shrimp)',
        description: 'A crispy golden-brown flour tortilla, filled with sizzling shrimp fajitas. Topped with lettuce, tomatoes, shredded cheese, sour cream and guacamole.',
        price: '$12.49',
        category: 'ensaladas',
      },
      {
        id: 'grilled-chicken-salad',
        name: 'Grilled Chicken Salad',
        description: 'Grilled chunks of chicken over a bed of fresh lettuce, tomatoes, onions and bell peppers. Topped with shredded cheese. Your choice of dressing on the side.',
        price: '$10.99',
        category: 'ensaladas',
      },
      {
        id: 'grilled-shrimp-salad',
        name: 'Grilled Shrimp Salad',
        description: 'Grilled shrimp over a bed of fresh lettuce, tomatoes, onions and bell peppers. Topped with shredded cheese.',
        price: '$12.49',
        category: 'ensaladas',
      },
      {
        id: 'tossed-salad',
        name: 'Tossed Salad',
        description: 'Fresh bed of lettuce with tomatoes and onions.',
        price: '$4.25',
        category: 'ensaladas',
      }
    ]
  },
  {
    id: 'enchiladas',
    title: 'Enchiladas',
    items: [
      {
        id: 'enchiladas-rancheras',
        name: 'Enchiladas Rancheras',
        description: 'Two corn tortillas filled with cheese topped with red enchilada sauce and beef tips cooked with onions, tomatoes and peppers. Served with rice, beans, lettuce and sour cream.',
        price: '$10.99',
        category: 'enchiladas',
      },
      {
        id: 'enchiladas-supremas',
        name: 'Enchiladas Supremas',
        description: 'Four corn tortillas, one filled with shredded chicken, one with ground beef, one with cheese and one with refried beans. Topped with red enchilada sauce, lettuce, tomato, sour cream and shredded cheese.',
        price: '$10.99',
        category: 'enchiladas',
        featured: true,
      },
      {
        id: 'enchiladas-verdes',
        name: 'Enchiladas Verdes',
        description: 'Four corn tortillas filled with shredded chicken. Topped with green tomatillo sauce, lettuce, guacamole, shredded cheese and a slice of tomato.',
        price: '$10.99',
        category: 'enchiladas',
      },
      {
        id: 'enchiladas-suizas-dinner',
        name: 'Enchiladas Suizas',
        description: 'Four bean enchiladas topped with tender grilled chicken breast strips with grilled onions, peppers and tomatoes and cheese sauce.',
        price: '$12.25',
        category: 'enchiladas',
      }
    ]
  },
  {
    id: 'vegetarian',
    title: 'Platos Vegetarianos',
    items: [
      {
        id: 'veg-a',
        name: 'Vegetarian Combo A',
        description: 'One Chalupa, One Cheese Enchilada and Refried Beans.',
        price: '$10.99',
        category: 'vegetarian',
      },
      {
        id: 'veg-b',
        name: 'Vegetarian Combo B',
        description: 'Two Bean Burritos Covered with Our Queso Dip Sauce.',
        price: '$10.99',
        category: 'vegetarian',
      },
      {
        id: 'veg-c',
        name: 'Vegetarian Combo C',
        description: 'One Bean Burrito, One Cheese Enchilada and One Bean Tostada, Topped with Lettuce, Sour Cream and a Slice of Tomato.',
        price: '$10.99',
        category: 'vegetarian',
      },
      {
        id: 'veg-d',
        name: 'Vegetarian Combo D',
        description: 'One Bean Burrito, One Cheese Quesadilla and One Chalupa.',
        price: '$10.99',
        category: 'vegetarian',
      },
      {
        id: 'garden-quesadilla',
        name: 'Garden Quesadilla',
        description: 'Two large flour tortillas filled with melted cheese, grilled peppers, onions, tomatoes and mushrooms. Served with sour cream and pico de gallo.',
        price: '$10.99',
        category: 'vegetarian',
      },
      {
        id: 'vegetarian-nachos',
        name: 'Vegetarian Nachos',
        description: 'Tortilla chips and grilled tomatoes, onions, bell peppers and mushrooms covered with melted cheese.',
        price: '$10.99',
        category: 'vegetarian',
      },
      {
        id: 'vegetarian-fajitas',
        name: 'Vegetarian Fajitas',
        description: 'Grilled tomatoes, onions, bell peppers, mushrooms and pineapple. Served with lettuce, guacamole, sour cream, pico de gallo, rice, beans and tortillas.',
        price: '$11.25',
        category: 'vegetarian',
      }
    ]
  },
  {
    id: 'los-favoritos',
    title: 'Los Favoritos',
    items: [
      {
        id: 'chimichanga-fav',
        name: 'Chimichanga',
        description: 'A flour tortilla stuffed with your choice of shredded chicken or beef tips, cooked with onions, peppers and tomatoes, deep fried to a golden brown. Covered with our queso dip sauce, served with rice, refried beans, lettuce, guacamole, sour cream, shredded cheese and pico de gallo.',
        price: '$11.99',
        category: 'los-favoritos',
        featured: true,
      },
      {
        id: 'fajita-chimichanga-fav',
        name: 'Fajita Chimichanga',
        description: 'A flour tortilla stuffed with grilled chicken or steak, onions, peppers and tomatoes, deep fried to a golden brown. Covered with our queso dip, served with rice, refried beans, lettuce, guacamole, sour cream, and a slice of tomato.',
        price: '$12.75',
        category: 'los-favoritos',
      },
      {
        id: 'chimichangas-dobles',
        name: 'Chimichangas Dobles',
        description: 'One chicken and one beef chimichanga served with guacamole, sour cream, pico de gallo and lettuce.',
        price: '$11.99',
        category: 'los-favoritos',
      },
      {
        id: 'taquitos-mexicanos-fav',
        name: 'Taquitos Mexicanos',
        description: 'Four corn tortillas filled with your choice of shredded chicken or beef, cooked with onions, peppers and tomatoes, wrapped and deep fried to a golden brown. Served with rice, refried beans, lettuce, pico de gallo, guacamole and sour cream.',
        price: '$11.99',
        category: 'los-favoritos',
      },
      {
        id: 'fiesta-dinner',
        name: 'Fiesta Dinner',
        description: 'A little of everything! One ground beef taco, one enchilada, one chile relleno, one pork tamale and one chalupa. Served with rice and refried beans.',
        price: '$15.99',
        category: 'los-favoritos',
        featured: true,
      },
      {
        id: 'angus-cheeseburger',
        name: 'Angus Cheeseburger',
        description: 'Served with lettuce, tomato, pickles, onion and fries.',
        price: '$10.99',
        category: 'los-favoritos',
      },
      {
        id: 'side-rice-beans-add',
        name: 'Add Rice and Beans',
        description: 'Add a side of rice and beans to any favorite.',
        price: '$1.99',
        category: 'los-favoritos',
      }
    ]
  },
  {
    id: 'combinations',
    title: 'Combination Dinners',
    items: [
      {
        id: 'combo-two',
        name: 'Choose Two Items',
        description: 'Choose two different items: Burrito, Enchilada, Chile Relleno, Chalupa, Tamale, Tostada, Hard Shell Taco, Soft Shell Taco, or Chile con Queso. Includes rice and beans.',
        price: '$10.75',
        category: 'combinations',
      },
      {
        id: 'combo-three',
        name: 'Choose Three Items',
        description: 'Choose three different items: Burrito, Enchilada, Chile Relleno, Chalupa, Tamale, Tostada, Hard Shell Taco, Soft Shell Taco, or Chile con Queso. Includes rice and beans.',
        price: '$12.99',
        category: 'combinations',
      }
    ]
  },
  {
    id: 'street-food',
    title: 'Authentic Mexican Street Food',
    items: [
      {
        id: 'menudo',
        name: 'Menudo',
        description: 'Traditional Mexican soup made with beef stomach (tripe) in broth with a red chili pepper base.',
        price: '$12.99',
        category: 'street-food',
        featured: true,
      },
      {
        id: 'burrito-al-pastor-street',
        name: 'Burrito al Pastor',
        description: 'Diced grilled pork, marinated in a savory family recipe al pastor marinade with diced pineapple for a nice contrast of flavors all wrapped up inside of a burrito covered in cheese sauce. Served with rice, pico de gallo and salsa.',
        price: '$11.99',
        category: 'street-food',
      },
      {
        id: 'quesadilla-al-pastor-street',
        name: 'Quesadilla al Pastor',
        description: 'Grilled al pastor pork with pineapple and melted cheese, served with rice, pico de gallo and salsa.',
        price: '$11.99',
        category: 'street-food',
      },
      {
        id: 'pozole-soup',
        name: 'Homemade Pozole Soup',
        description: 'Savory Mexican soup made from scratch from a family recipe. Shredded pork and hominy in a savory red broth. Served with shredded cabbage, sliced radishes, lime and a special spicy salsa.',
        price: '$12.49',
        category: 'street-food',
      },
      {
        id: 'torta-ahogada',
        name: 'Torta Ahogada',
        description: 'A classic from Guadalajara! A delicious sandwich filled with carnitas pork meat and pickled onions, smothered in spicy red salsa.',
        price: '$11.99',
        category: 'street-food',
      },
      {
        id: 'pambazos',
        name: 'Pambazos',
        description: 'A Perez family favorite! Sour dough bread, dipped in mole sauce, grilled and filled with refried beans and chorizo or shredded chicken. Served with sliced avocado, lettuce, onion, sour cream, jalapeños, beans, cheese and salsa verde.',
        price: '$11.99',
        category: 'street-food',
      },
      {
        id: 'tortas-planchadas',
        name: 'Tortas Planchadas',
        description: 'Cheese and your choice of shredded chicken, pastor pork, grilled steak or chorizo, grilled inside of sourdough bread. Served with mayo, lettuce, tomatoes, onions, avocado, jalapeños and fries.',
        price: '$11.99',
        category: 'street-food',
      },
      {
        id: 'street-tacos-item',
        name: 'Street Tacos',
        description: 'Grilled steak, chicken, chorizo, shrimp, carnitas, or al pastor pork (with pineapple) on a corn tortilla topped with onions, cilantro and a side of tomatillo sauce.',
        price: '$3.25 each',
        category: 'street-food',
      }
    ]
  },
  {
    id: 'carne',
    title: 'Carne (Beef)',
    items: [
      {
        id: 'bistec-ranchero',
        name: 'Bistec Ranchero',
        description: 'A Ribeye beef steak grilled and topped with our spicy Ranchero red sauce. Served with rice, refried beans and tortillas.',
        price: '$18.49',
        category: 'carne',
      },
      {
        id: 'bistec-mexicano',
        name: 'Bistec Mexicano',
        description: 'A grilled Ribeye beef steak topped with grilled onions, tomatoes and peppers. Served with rice, beans and tortillas.',
        price: '$18.49',
        category: 'carne',
      },
      {
        id: 'steak-tampiquena',
        name: 'Steak A La Tampiqueña',
        description: 'A grilled Ribeye beef steak, served with rice, refried beans and a side tossed salad.',
        price: '$18.99',
        category: 'carne',
      },
      {
        id: 'steak-fries',
        name: 'Steak and Fries',
        description: 'A grilled Ribeye beef steak, served with french fries.',
        price: '$18.99',
        category: 'carne',
      },
      {
        id: 'carne-asada-plate',
        name: 'Carne Asada',
        description: 'Thinly sliced grilled steak. Served with rice, refried beans, guacamole and tortillas.',
        price: '$13.49',
        category: 'carne',
        featured: true,
      },
      {
        id: 'chile-colorado',
        name: 'Chile Colorado',
        description: 'Grilled strips of steak cooked with our Ranchero sauce. Served with rice, refried beans and tortillas.',
        price: '$13.49',
        category: 'carne',
      },
      {
        id: 'chile-verde-carne',
        name: 'Chile Verde',
        description: 'Grilled strips of steak cooked with our green chile sauce. Served with rice, refried beans and tortillas.',
        price: '$13.49',
        category: 'carne',
      },
      {
        id: 'carne-con-queso',
        name: 'Carne con Queso',
        description: 'Grilled strips of steak covered with queso dip sauce. Served with tortillas.',
        price: '$13.49',
        category: 'carne',
      },
      {
        id: 'tacos-carne-asada-plate',
        name: 'Tacos de Carne Asada',
        description: 'Three tortillas filled with grilled steak strips. Served with refried beans, pico de gallo and tomatillo sauce.',
        price: '$11.99',
        category: 'carne',
      }
    ]
  },
  {
    id: 'pollo',
    title: 'Pollo (Chicken)',
    items: [
      {
        id: 'pollo-loco',
        name: 'Pollo Loco',
        description: 'A tender grilled chicken breast served with lettuce, tomatoes, sour cream, rice, refried beans and flour tortillas.',
        price: '$12.99',
        category: 'pollo',
      },
      {
        id: 'pollo-monterrey',
        name: 'Pollo Monterrey',
        description: 'Tender grilled chicken breast strips grilled with onions, peppers and tomatoes. Served with rice, beans and tortillas.',
        price: '$13.25',
        category: 'pollo',
      },
      {
        id: 'pollo-vandido',
        name: 'Pollo Vandido',
        description: 'Tender grilled chicken breast strips and Chorizo (spicy Mexican sausage) topped with cheese dip, served with lettuce, sour cream, guacamole, rice, refried beans and flour tortillas.',
        price: '$13.75',
        category: 'pollo',
        featured: true,
      },
      {
        id: 'pollo-con-queso-plate',
        name: 'Pollo Con Queso',
        description: 'Tender strips of chicken breast grilled and covered with our queso dip sauce. Served with flour tortillas.',
        price: '$12.99',
        category: 'pollo',
      },
      {
        id: 'arroz-con-pollo-plate',
        name: 'Arroz con Pollo',
        description: 'Tender strips of grilled chicken breast, covered with our queso dip with a side of rice. Served with lettuce, guacamole, sour cream and flour tortillas.',
        price: '$13.25',
        category: 'pollo',
      },
      {
        id: 'mushroom-chicken',
        name: 'Mushroom Chicken',
        description: 'Tender grilled chicken breast strips topped with grilled mushrooms, covered with cheese dip. Served with rice, refried beans and flour tortillas.',
        price: '$13.75',
        category: 'pollo',
      },
      {
        id: 'pollo-suizo',
        name: 'Pollo Suizo',
        description: 'Tender grilled chicken breast strips with grilled onions, peppers and tomatoes topped with cheese sauce. Served with rice and tortillas.',
        price: '$13.75',
        category: 'pollo',
      },
      {
        id: 'add-shrimp-6',
        name: 'Add Shrimp (6)',
        description: 'Add 6 grilled shrimp to any dish.',
        price: '$4.25',
        category: 'pollo',
      },
      {
        id: 'jalisco-especial',
        name: 'Jalisco Especial',
        description: 'A tender grilled chicken breast and a thinly sliced grilled steak and 3 jumbo shrimp. Served with lettuce, guacamole, pico de gallo, rice, refried beans and flour tortillas.',
        price: '$13.99',
        category: 'pollo',
        featured: true,
      }
    ]
  },
  {
    id: 'mariscos',
    title: 'Mariscos (Seafood)',
    items: [
      {
        id: 'camarones-diabla',
        name: 'Camarones a la Diabla',
        description: 'A dozen grilled shrimp marinated in garlic and grilled with butter. Smothered in our special Diabla hot sauce. Served with rice, refried beans and tortillas.',
        price: '$13.99',
        category: 'mariscos',
        featured: true,
      },
      {
        id: 'camarones-mojo-ajo',
        name: 'Camarones al Mojo de Ajo',
        description: 'A dozen shrimp grilled with our special butter garlic sauce. Served with rice, refried beans and tortillas.',
        price: '$13.99',
        category: 'mariscos',
      },
      {
        id: 'camarones-mexicanos',
        name: 'Camarones Mexicanos',
        description: 'A dozen shrimp grilled with tomatoes, onions, fresh jalapeño peppers. Served with rice.',
        price: '$13.99',
        category: 'mariscos',
      },
      {
        id: 'enchiladas-camaron-plate',
        name: 'Enchiladas de Camarón',
        description: 'Three corn tortillas filled with grilled shrimp covered in our queso dip. Topped with lettuce and sour cream. Served with rice.',
        price: '$12.99',
        category: 'mariscos',
      },
      {
        id: 'shrimp-burrito-plate',
        name: 'Shrimp Burrito',
        description: 'A burrito stuffed with grilled shrimp, peppers, onions, and tomatoes, covered in our queso dip sauce. Topped with lettuce and sour cream. Served with rice.',
        price: '$13.49',
        category: 'mariscos',
      },
      {
        id: 'fish-fillet',
        name: 'Fish Fillet',
        description: 'Fresh Tilapia, seasoned and grilled to perfection. Served with rice, lettuce, tomatoes, cheese, sour cream and tortillas.',
        price: '$13.49',
        category: 'mariscos',
      },
      {
        id: 'shrimp-chimichanga-plate',
        name: 'Shrimp Chimichanga',
        description: 'A flour tortilla stuffed with grilled shrimp, onions, peppers and tomatoes, deep fried to a golden brown. Covered with our queso dip sauce, served with rice, refried beans, lettuce, guacamole, sour cream, and a slice of tomato.',
        price: '$13.49',
        category: 'mariscos',
      },
      {
        id: 'fish-tacos-plate',
        name: 'Fish Tacos',
        description: 'Three tortillas topped with seasoned grilled tilapia fillets. Served with beans, brown tomatillo sauce and pico de gallo.',
        price: '$12.75',
        category: 'mariscos',
      },
      {
        id: 'camarones-con-queso-plate',
        name: 'Camarones con Queso',
        description: 'A dozen seasoned grilled shrimp covered in our queso dip sauce. Served with rice, lettuce guacamole, sour cream and flour tortillas.',
        price: '$13.99',
        category: 'mariscos',
      }
    ]
  },
  {
    id: 'fajitas-and-more',
    title: 'Fajitas and More',
    items: [
      {
        id: 'fajitas-single',
        name: 'Fajitas Single',
        description: 'Strips of your choice of beef or chicken grilled with peppers, tomatoes, and onions. Served with lettuce, guacamole, sour cream, pico de gallo, rice, beans and tortillas.',
        price: '$13.99',
        category: 'fajitas-and-more',
      },
      {
        id: 'fajitas-double',
        name: 'Fajitas Double',
        description: 'Double portion of our sizzling fajitas. Choice of beef or chicken.',
        price: '$27.49',
        category: 'fajitas-and-more',
      },
      {
        id: 'shrimp-fajitas-single',
        name: 'Shrimp Fajitas Single',
        description: 'Sizzling shrimp grilled with peppers, tomatoes, and onions. Served with lettuce, guacamole, sour cream, pico de gallo, rice, beans and tortillas.',
        price: '$15.99',
        category: 'fajitas-and-more',
      },
      {
        id: 'shrimp-fajitas-double',
        name: 'Shrimp Fajitas Double',
        description: 'Double portion of our sizzling shrimp fajitas.',
        price: '$29.99',
        category: 'fajitas-and-more',
      },
      {
        id: 'combination-fajitas',
        name: 'Combination Fajitas',
        description: 'Steak, Chicken and Shrimp fajitas enough for two!',
        price: '$29.99',
        category: 'fajitas-and-more',
        featured: true,
      },
      {
        id: 'seafood-fajitas',
        name: 'Seafood Fajitas',
        description: 'Grilled Tilapia, shrimp and scallops, grilled with onions, tomatoes and peppers. Served with lettuce, pico de gallo, sour cream, guacamole, rice, refried beans and tortillas.',
        price: '$15.75',
        category: 'fajitas-and-more',
      },
      {
        id: 'fajitas-bravas-plate',
        name: 'Fajitas Bravas',
        description: 'Strips of chicken, steak, chorizo and shrimp grilled with bell peppers, tomatoes and onions. Served with refried beans, rice lettuce, guacamole, sour cream, pico de gallo and tortillas.',
        price: '$15.75',
        category: 'fajitas-and-more',
      },
      {
        id: 'molcajete-mexicano',
        name: 'Molcajete Mexicano',
        description: 'Served in a Mexican Stone Bowl, feeds 3! Carne Asada steak, two grilled chicken breasts, two pieces of carnitas, half dozen shrimp and chorizo. 3 side plates which include rice, refried beans, lettuce, pico de gallo, guacamole, sour cream, tomatillo salsa and tortillas.',
        price: '$41.99',
        category: 'fajitas-and-more',
        featured: true,
      },
      {
        id: 'carnitas-plate',
        name: 'Carnitas',
        description: 'Marinated pork tips, served with rice, refried beans, lettuce, guacamole, a tomato slice and tortillas.',
        price: '$13.75',
        category: 'fajitas-and-more',
      },
      {
        id: 'puerco-salsa-verde',
        name: 'Puerco en Salsa Verde',
        description: 'Shredded pork meat smothered in our spicy green salsa. Served with rice, refried beans and tortillas.',
        price: '$13.49',
        category: 'fajitas-and-more',
      }
    ]
  },
  {
    id: 'starters',
    title: 'Appetizers & Starters',
    items: [
      {
        id: 'cheese-dip',
        name: 'Cheese Dip',
        description: 'Our famous creamy white cheese dip served with fresh tortilla chips.',
        price: '$5.99',
        category: 'starters',
        featured: true,
      },
      {
        id: 'elotes',
        name: 'Elotes',
        description: 'Mexican street corn with mayo, cotija cheese, and chili powder.',
        price: '$6.50',
        category: 'starters',
        featured: true,
      },
      {
        id: 'chori-queso',
        name: 'Chori Queso',
        description: 'Melted cheese blended with spicy Mexican chorizo.',
        price: '$7.99',
        category: 'starters',
      },
      {
        id: 'el-bobs-dip',
        name: "El Bob's Dip",
        description: 'A hearty combo of steak, chorizo, and melted cheese.',
        price: '$9.50',
        category: 'starters',
      }
    ]
  },
  {
    id: 'drinks',
    title: 'Drinks & Margaritas',
    items: [
      {
        id: 'lime-margarita',
        name: 'Lime Margarita',
        description: 'Frozen or On The Rocks. Small $3.99, Medium $5.99, Monster $10.99, Pitcher $14.99.',
        price: 'From $3.99',
        category: 'drinks',
        featured: true,
      },
      {
        id: 'texas-margarita',
        name: 'Texas Margarita',
        description: '28 oz. A delicious lime margarita made with our House Gold Tequila and Grand Gala.',
        price: '$9.49',
        category: 'drinks',
      },
      {
        id: 'flavored-margarita',
        name: 'Flavored Margarita',
        description: 'Strawberry, Watermelon, Peach, or Mango. Frozen or On The Rocks. Small $4.50, Medium $5.99, Monster $11.50, Pitcher $16.99.',
        price: 'From $4.50',
        category: 'drinks',
      },
      {
        id: 'skinny-margarita',
        name: 'Skinny Margarita',
        description: 'Lower-calorie, no-mix version of our delicious margaritas.',
        price: '$8.49',
        category: 'drinks',
      },
      {
        id: 'daiquiris',
        name: 'Daiquiris',
        description: 'Strawberry, Mango, Peach, or Piña Colada.',
        price: '$5.99',
        category: 'drinks',
      },
      {
        id: 'virgin-daiquiris',
        name: 'Virgin Daiquiris',
        description: 'Strawberry, Mango, or Peach.',
        price: '$4.25',
        category: 'drinks',
      },
      {
        id: 'jarrito-loco',
        name: 'Jarrito Loco',
        description: 'A refreshing blend of orange, grapefruit and lime juices with Hornitos tequila served in an artisanal clay mug with a salted rim.',
        price: '$8.49',
        category: 'drinks',
        featured: true,
      },
      {
        id: 'imported-beer',
        name: 'Imported Bottled Beer',
        description: 'Corona Extra, Corona Light, Modelo Negra, Modelo Especial, Tecate, Dos XX, Dos XX Amber.',
        price: '$3.99',
        category: 'drinks',
      },
      {
        id: 'corona-jumbo',
        name: 'Corona Jumbo (32 oz)',
        description: 'A massive 32 oz Corona.',
        price: '$8.50',
        category: 'drinks',
      },
      {
        id: 'domestic-beer',
        name: 'Domestic Bottled Beer',
        description: 'Budweiser, Bud Light, Coors Light, Miller Lite, Michelob Ultra, Busch.',
        price: '$3.25',
        category: 'drinks',
      },
      {
        id: 'on-tap-domestic',
        name: 'On Tap (Domestic)',
        description: 'Bud Light, Miller Lite. 12 oz $2.75, 20 oz $4.99, 32 oz $7.99, Pitcher $11.99.',
        price: 'From $2.75',
        category: 'drinks',
      },
      {
        id: 'on-tap-premium',
        name: 'On Tap (Premium)',
        description: 'Dos XX, Modelo Especial, Blue Moon. 12 oz $3.49, 20 oz $5.99, 32 oz $8.75, Pitcher $12.49.',
        price: 'From $3.49',
        category: 'drinks',
      },
      {
        id: 'wine-glass',
        name: 'Wine',
        description: 'Sangria, Chablis, Rose, White Zinfandel, Chardonnay.',
        price: '$5.49',
        category: 'drinks',
      },
      {
        id: 'soft-drinks',
        name: 'Coke Products, Lemonade and Milk',
        description: 'Coke, Diet Coke, Sprite, Pibb, Mello Yello, Minute Maid Lemonade, Fanta Orange. Complimentary refills on Coke products.',
        price: '$2.99',
        category: 'drinks',
      },
      {
        id: 'strawberry-lemonade',
        name: 'Strawberry Lemonade',
        description: 'Fresh and sweet strawberry lemonade.',
        price: '$3.75',
        category: 'drinks',
      },
      {
        id: 'tea-sweet-unsweet',
        name: 'Sweet or Unsweet Tea',
        description: 'Complimentary refills.',
        price: '$2.99',
        category: 'drinks',
      },
      {
        id: 'horchata-jamaica',
        name: 'Homemade Horchata or Jamaica',
        description: 'Traditional Mexican sweet rice milk or hibiscus tea.',
        price: '$3.50',
        category: 'drinks',
      }
    ]
  },
  {
    id: 'desserts',
    title: 'Los Postres (Desserts)',
    items: [
      {
        id: 'sopapilla',
        name: 'Sopapilla',
        description: 'A flour tortilla deep fried to a golden brown. Topped with butter, honey and cinnamon. Add ice cream for 99¢ more.',
        price: '$4.25',
        category: 'desserts',
      },
      {
        id: 'flan',
        name: 'Flan',
        description: 'A traditional Mexican creamy caramel custard. Topped with whipped topping and a cherry on top.',
        price: '$4.25',
        category: 'desserts',
        featured: true,
      },
      {
        id: 'fried-ice-cream',
        name: 'Fried Ice Cream',
        description: 'A big scoop of ice cream covered in a delicious mixture of cereals and cinnamon, then deep fried to a golden brown. Served in a crispy bowl, topped with honey, whipped topping, chocolate syrup and a cherry on top.',
        price: '$5.99',
        category: 'desserts',
        featured: true,
      },
      {
        id: 'banana-chimi',
        name: 'Banana Chimi',
        description: 'A banana wrapped in a golden brown crispy shell. Topped with Cajeta, a delicious Mexican caramel syrup, and whipped topping. Served with a scoop of ice cream with chocolate syrup on top.',
        price: '$5.99',
        category: 'desserts',
      }
    ]
  }
];
